### ISSUE TITLE
can InGVIO run without GNSS?

### ISSUE THREAD

**Issue by iceberg1369** [ChangwuLiu/InGVIO#2]
I was wondering whether InGVIO can run without  GNSS, or somehow tolerate GPS outage? any statics?

**Comment by ChangwuLiu** [comment]
Of course,  the linked paper has mentioned the performance of pure VIO. To run without GNSS, just simply disable GNSS in the config file. The invariant VIO (InVIO) has been tested in all our fixed-wing datasets (see link). Also, you can run InVIO with the 'sports_field.bag' and 'complex_environment.bag' of the GVINS datasets. Besides these two datasets, to deploy InVIO on other datasets (like EuRoC), you should provide your own config files in our format (I didn't mention other VIO datasets because I assume the GVINS and fixed-wing datasets have already covered more chanllenging cases.).
